config/routes.rb
Infoport::Application.routes.draw do
  resources :ports
  resources :entities

match 'frontend/keys/:id' => 'frontend#keys'
match 'frontend/entities/:id' => 'frontend#entities'

get  'frontend/keys'
get  'frontend/entities'
get  'frontend/index'
get  'frontend/get_linked_by_keys'
post 'frontend/search'
post 'frontend/sel_details'
post 'frontend/show_timeline'

get 'dyninterface/showsave'
get 'dyninterface/showload'

get 'test/test1'
get 'test/sparqlendp'
post 'test/sparqlendp'
post 'test/showdialog'
get 'test/showd2'
end

app/views/layouts/_entity_details.html.erb
<%# coding: utf-8 %>
 <div class="row">
 
 <h4 ><%= t :entity_details_title %></h2>
	
			<!-- PHOTO -->
			<div class="small-3 columns">
				<!-- div  style="width: 10px; height: 190px;" -->
				<% if @Person.img %>
				<a class="th radius" style=" height: 120px; width: 100px; background: url(<%= @Person.img %>) no-repeat center center; background-size: cover;" href="http://www.hse.ru/org/persons/<%= @Person.uri.split('#').last %>" />
									<!-- img src="<%= @Person.img %>" height="80" width="80" alt="Личное фото" -->
				<% end %>
				</a>
				<!-- /div -->
			</div>
			
			<div class="small-9 columns">
				<div class="panel radius" style="height: 120px"> 
					<a  class="link" style="text-decoration:underline" href="http://www.hse.ru/org/persons/<%= @Person.uri.split('#').last %>" >
							<bold> <%= "#{@Person.lastname} #{@Person.firstname} #{@Person.middlename}" %> </bold>
					</a>		
							<br>
							<% @Person.units.each do |u| %>
			      				<%= u %> <br>
			    			<% end%>
			    </div>			
		   </div>
		
<div class="small-12 columns">
	<div class="panel radius"> <h4 class="subheader"><%= t :entity_details_taxonomy_title %></h2>			
				<%= select_tag "found_entities", options_for_select(@Person.taxo_topics), html_options = {:size => 5} %>
	</div>
</div>

	<div class="small-12 columns">
	  
			<!-- KEYWORDS CLOUD -- BEGIN -->
	     	<div class="panel radius"> 
				<h4 class="subheader"> <%= t :entity_details_keys_title %></h2>
				<div class="panel radius"  id="cloud_container" style=" width: 107%; height: 500px;"> </div>
			</div>	
					  <script type="text/javascript" id ="keyscloud" >
				      /*!
				       * Create an array of word objects, each representing a word in the cloud
				       */
				      
				      	var word_array = [
				     
				     <% if  ! @Person.keywords.nil? %>
					      <% @Person.keywords.each_with_index do |k, i| %>
					      		{text: "<%= k %> ", weight: 1,  link:"<%= frontend_get_linked_by_keys_path %>?q=<%=k%>", html: { style: "font-size: 9pt" }   }
					      		<% if i != @Person.keywords.size - 1 %>
					      		,
					      		<% end %>
					      <% end %>
				      <% end %>
				          // ...as many words as you want
				      ];

					 $("#cloud_container").jQCloud(word_array);
					 
					 
				     // $(function() {
				
				        // When DOM is ready, select the container element and call the jQCloud method, passing the array of words as the first argument.
				     //   if (typeof word_array === "undefined") {} else { $("#cloud_container").jQCloud(word_array); } 
				        //$("#cloud_container").jQCloud(word_array);
				   //   });
				    </script> 
   </div>


		<!-- KEYWORDS CLOUD -- END -->
		
	<div class="small-12 columns">
			   
				<!-- TIME LINE PERIOD SELECTION --> 
				<%if @StartDateSelector.nil? %>
					<% @StartDateSelector = Date.today %>
				<%end%>
				<%if @EndDateSelector.nil? %>
					<% @EndDateSelector = (Date.today + 1) %>
				<%end%>
																
				<%= form_tag 'show_timeline' do %>
				<h4 class="subheader"><%= t :entity_details_timeline_title %></h4>
				<div class="small-4 columns"><label for="start_month" style= " width: 150px " ><%= t :entity_details_timeline_start_msg %></label> 
					<input name ="start_date" value ="<%= I18n.l(@StartDateSelector) %>" type="date" style= " width: 130px " /></div>
				<div class="small-4 columns"><label for="end_month"><%= t :entity_details_timeline_end_msg %></label> 
					<input name ="end_date" value ="<%= I18n.l(@EndDateSelector) %>" type="date" style= " width: 130px " /></div>	
				<%= hidden_field_tag "personuri", @Person.uri %>
				<div class="small-4 columns"><%= submit_tag t(:entity_details_timeline_button_update), :class => "button round"  %></div>
				<% end %>	
		     
	</div>	
		<div class="small-12 columns">
			   			<% if @K_int_TimeLine.present? %>
						<div class="panel radius">
								<%= render 'layouts/keywords_timeline',  :timeline => @K_int_TimeLine, :startdate => @StartDateSelector, :enddate => @EndDateSelector %>
						</div>
						<%end%>
		</div>				
				
		
</div>	




		<!-- TAGS CLOUD --> 
					<!--      
			        {text: "Lorem", weight: 13, link: "https://github.com/lucaong/jQCloud"},
			        {text: "Ipsum", weight: 10.5, link: "http://jquery.com/"},
			        {text: "Dolor", weight: 9.4},
			        {text: "Sit", weight: 8},
			        {text: "Amet", weight: 6.2},
			        {text: "Consectetur", weight: 5},
			        {text: "Adipiscing", weight: 5},
			        {text: "Elit", weight: 5},
			        {text: "Nam et", weight: 5},
			        {text: "Leo", weight: 4},
			        {text: "Sapien", weight: 4, link: "http://www.lucaongaro.eu/"},
			        {text: "Pellentesque", weight: 3},
			        {text: "habitant", weight: 3},
			        {text: "morbi", weight: 3},
			        {text: "tristisque", weight: 3},
			        {text: "senectus", weight: 3},
			        {text: "et netus", weight: 3},
			        {text: "et malesuada", weight: 3},
			        {text: "fames", weight: 2},
			        {text: "ac turpis", weight: 2},
			        {text: "egestas", weight: 2},
			        {text: "Aenean", weight: 2},
			        {text: "vestibulum", weight: 2},
			        {text: "elit", weight: 2},
			        {text: "sit amet", weight: 2},
			        {text: "metus", weight: 2},
			        {text: "adipiscing", weight: 2},
			        {text: "ut ultrices", weight: 2},
			        {text: "justo", weight: 1},
			        {text: "dictum", weight: 1},
			        {text: "Ut et leo", weight: 1},
			        {text: "metus", weight: 1},
			        {text: "at molestie", weight: 1},
			        {text: "purus", weight: 1},
			        {text: "Curabitur", weight: 1},
			        {text: "diam", weight: 1},
			        {text: "dui", weight: 1},
			        {text: "ullamcorper", weight: 1},
			        {text: "id vuluptate ut", weight: 1},
			        {text: "mattis", weight: 1},
			        {text: "et nulla", weight: 1},
			        {text: "Sed", weight: 1}
			-->        		

		

app/views/layouts/_entity_summary.html.erb
<div class="row">

		<h4 class="subheader"><%= t :summary_title %></h4>		
			<!-- SORTED KEYWORDS WITH OCCURENCIES-->
	
<% if @Summary.present? %>
<%= t :summary_satisfied_msg_prefix %> <%= @EntityCount %> <%= t :summary_satisfied_msg_suffix %>
	<table>
		<% @Summary["hist"].each do |s| %>
			<% if !s[:l].nil? %>
			<tr> <td> <a  href="<%= frontend_get_linked_by_keys_path %>?q=<%= s[:l] %>">   <%= s[:l] %>  </a>  </td><td><%= s[:lC] %></td></tr>
			<%end%>
		<%end%>
	</table>
<%end%>
</div>

app/views/layouts/_footer.html.erb
<footer> </footer>
<%= raw t :app_copyright %>
</div>
<p>&nbsp;</p>

app/views/layouts/_found_entities.html.erb
<%# this is a partial for listing found entities %>



<%#= @e_libkeys %>

<%#= @query_text %>

<%= form_tag 'sel_details' do %>
<div class="row">
	<div class="small-11  columns">	
		<%if perns.present?%>
	    	<% persons_array = perns.map { |p| ["#{p.lastname} #{p.firstname} #{p.middlename}", p.uri] } %>
	    <%else%>
	    	<% persons_array = [] %>
	    <%end%>
		<%= select_tag "found_entities", options_for_select(persons_array), html_options = {:size => 10} %>
	</div>
	<div class="small-1  columns">
		<% if @EntityCount > Infoport::Application.config.found_entities_per_page  %>			    
		    <% if @CurrentPage > 1 %>
		     <%= button_tag "<", :name => 'commit', :value => 'prevpage', :type => "submit", :class => "button small", :style => "width:10px;"  %>
		    <% end %>
		    
		    <% if @CurrentPage * Infoport::Application.config.found_entities_per_page < @EntityCount %>
			    <%= button_tag ">", :name => 'commit', :value => 'nextpage', :type => "submit", :class => "button small", :style => "width:10px;"  %>
			<%end %>	    	
		<%end %>
	</div>
</div>  
  <div class="row">
  	  <div class="small-2  columns"> 
	  <%= button_tag t(:result_list_button_details),:name => 'commit', :value => 'details', :type => "submit", :class => "button round"  %>
	  </div>
	  
	  <div class="small-5  columns"/>
	  
	  <div class="small-2  columns"> 
	  <%= button_tag t(:result_list_button_summary),:name => 'commit', :value => 'summary', :type => "submit", :class => "button round"  %>
	  </div>
	  <div class="small-1  columns"/>
	  
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
</header>
<div id="logo">
	<div id="logo_text">
		<!-- class="logo_colour", allows you to change the colour of the text -->
		<h2>&nbsp;&nbsp;<%= t :title %> </h2> 
		
	</div>
</div>

app/views/layouts/_keywords_timeline.html.erb
<% if timeline.present? %>
<% last_value = "" %>
<% events_count = 0 %>

<table width="100%">
	<tr><td width="20%"></td><td width="80%"><div style = "text-align:left; vertical-align:center; height: 10px; float:left">
		<%= I18n.l (startdate) %></div> <div style = " vertical-align: center; height: 10px; float:right; text-align:right "><%= I18n.l(enddate) %></div></td></tr>
    <% timeline.each do |k| %>
		<%if last_value != k[:value] %>
		    <% if last_value != "" %></div></td></tr> <% end %>
		    <% last_value = k[:value] %>
		    <%# events_count = 0 %>
		    <tr><td width="20%"><div style="height: 50px; overflow: hidden"><small><%=k[:value]%>|  <%=k[:start]%> | <%=k[:end]%> </small></div></td>
		    <td width="80%" height="20px"> <div style="height: 50px; width:100%; position:relative">
    	<%end %>
    	<div align="left" name="l1" style = " background-color:#e<%= (99989 + events_count* 3).to_s(16) %>; width: <%= (k[:end] - k[:start]) * 3 %>px; height: 5px; position:absolute; left:<%=k[:start] * 3 %>px; top:25px" >
			<!-- img style = "height:4px; width:50px" src = "/assets/scale_b.png" #003366 / --> 
		</div>	
		<% events_count = events_count + 1 %>
    <% end %> 
</table>
<%end%>

app/views/layouts/_navig.html.erb
<!--
<nav> 
	
	
<div id= "nav_user" >
        <%# if user_signed_in? %>
          Logged in as <strong><%#= current_user.email %></strong>.
          <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%#= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link'  %>
        <%# else %>
          <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <%# end %>
</div>
-->

<nav class="top-bar">
<!-- ul class="title-area" -->
    <!-- Title Area -->
    <!--
    <li class="name">
      <h1><a href="#">Top Bar Title </a></h1>
    </li>
    -->
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <!-- li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
-->

<section class="top-bar-section" >

    <!-- Left Nav Section -->
    <ul class="left">		 
      <li class="divider"> </li>
      <li class="active">  <%= link_to t(:menu_home) , :controller => 'frontend', :action=>'index'%></li>
      <li class="divider"></li>
      <li class="inactive"><a href="#"><%= t :menu_settings %></a></li>
      <li class="divider"></li>
      <li class="active"> <%= link_to t(:menu_about) , '#', "data-reveal-id" => "aboutModal" %> </li>
    <ui/>
</section>
</nav>

<div id="aboutModal" class="reveal-modal" style="width:590px" >

   <div style="float:left;font-size: 14pt; vertical-align: middle; text-align: center">
   <center>	<%= image_tag "infoport_large.png", :width=>"80%", :height=>"80%" %></center></div>
   <br>
  
  <p><center><%= image_tag "infoportfamily_large.png", :width=>"50%", :height=>"50%" %>
  	  <br><small>"ИнфоПорт - элемент комплекса семантических web-приложений НИУ ВШЭ-Нижний Новгород"</small>
  	  <br>
  	  <p>НИУ ВШЭ - Нижний Новгород</p>
  <p>2013г.</p>
  </center></p> 
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/layouts/_search_conds.html.erb
<%# this is a partial for search conditions %>



<!--- -->
<!-- format START -->
<script type="text/javascript" id="search_cond"> 
 
    function movieFormatResult(movie) {
        var markup = "<table class='movie-result'><tr>";
      
      //  if (movie.posters !== undefined && movie.posters.thumbnail !== undefined) {
      //      markup += "<td class='movie-image'><img src='" + movie.posters.thumbnail + "'/></td>";
      //  }
      //  markup += "<td class='movie-info'><div class='movie-title'>" + movie.title + "</div>";
      //  if (movie.critics_consensus !== undefined) {
      //      markup += "<div class='movie-synopsis'>" + movie.critics_consensus + "</div>";
      //  }
      //  else if (movie.synopsis !== undefined) {
      //      markup += "<div class='movie-synopsis'>" + movie.synopsis + "</div>";
      //  }
       
        markup += "<td>aaaa</td></tr></table>"
        return markup;
    }
 
    function movieFormatSelection(movie) {
        return "aaaaa" ; //movie.title;
    }
 
 
 $(document).ready (function() {
 
 	$('#newkey').select2({
    placeholder: "введите слово",
    minimumInputLength: 1,
    ajax: { url: "<%= frontend_keys_path %>.json",
            dataType: 'json',
            data: function (term, page) {
              return {
		                key_pattern: term, // search term
		                page_limit: 10 
		             };
        },
        results: function (data, page) { // parse the results into the format expected by Select2.
            // since we are using custom formatting functions we do not need to alter remote JSON data
            return {results: data.keys, more: false};
        }
    },
    dropdownCssClass: "bigdrop", // apply css that makes the dropdown taller
    escapeMarkup: function (m) { return m; } // we do not want to escape markup since we are displaying html in results
});
});
 </script>
<!-- END -->

<%= form_tag 'search' do %>

<%= button_tag t(:search_panel_button_search),:name => 'commit', :value => 'search', :type => "submit", :class => "button round" , :style => "width:210px" %>

<%= field_set_tag t(:search_panel_keywords) do %>
	<input name="newkey" type="text" class="bigdrop" id="newkey" style="width:180px" value=""/>	
	<%#= text_field_tag 'newkey', 'Новое слово...' %>
	<%#= submit_tag 'Добавить', :value => 'keyadd', :class => "button small"  %>
	<%= button_tag t(:search_panel_button_keyadd), :name => 'commit', :value => 'keyadd', :type => "submit", :class => "button small"  %>
	<div>
		<small><%= t :search_panel_keyused %></small>
		<%= select_tag "keys", options_for_select(@keys), html_options = {:size => 4, :multiple => true } %>
	    <%#= submit_tag "Удалить", :value => 'keysdell', :class => "button small"  %> 
	    <%= button_tag t(:search_panel_button_keydel),:name => 'commit', :value => 'keysdell', :type => "submit", :class => "button small"  %>
	<div>
<% end %>

<% str = Taxonomy.instance.getTaxonomy %>
<%if str != nil %>
	<%= field_set_tag t(:search_panel_taxonomy) do %>
	<%# TODO  implement dynamic creation based on the datastorage %>
	
	
		<%= select_tag "new_e_libkey", options_for_select(str) %>
		<%#= submit_tag 'Добавить', :value => 'e_lib_keyadd', :class => "button small"  %> 
		<%= button_tag  t(:search_panel_button_topicadd),:name => 'commit', :value => 'e_lib_keyadd', :type => "submit", :class => "button small"  %>
		
		<div>
			<small><%= t :search_panel_topicused %></small>
			<%if Taxonomy.instance.getTaxonomy.present? && 	@e_libkeys.present? %>
				<% e_lib_array = Taxonomy.instance.getTaxonomy.select{|key, hash| @e_libkeys.include?(hash) } %>
			<% else %>
				<% e_lib_array = [] %>			
			<% end %>
			
			<%= select_tag "e_libkeys", options_for_select(e_lib_array), html_options = {:size => 4, :multiple => true } %>
	    	<%#= submit_tag "Удалить", :value => 'e_libkeysdell', :class => "button small"  %>
		    <%= button_tag t(:search_panel_button_topicdel),:name => 'commit', :value => 'e_lib_keysdel', :type => "submit", :class => "button small"  %>
		
		</div>
	<%end%>
<%end%>
	
<% str = Organization.instance.getOrganization %>
<% if str != nil %>	
	<%= field_set_tag t(:search_panel_search_level) do %>
			<%# TODO implement JS-based dynamic creation from data storage as it was suggested at http://pullmonkey.com/2008/03/30/dynamic-select-boxes-ruby-on-rails/ %>
			
			<%= select_tag "org_level", options_for_select(str, @org_level) %>
	<% end %>
<% end%>

	<%= button_tag t(:search_panel_button_search),:name => 'commit', :value => 'search', :type => "submit", :class => "button round" , :style => "width:210px" %>

	<div id="saveloadModal" class="reveal-modal" style="width:590px">
 		  <a class="close-reveal-modal">&#215;</a>
				  <div id="saveload_content"> </div>
	</div>
	
<% end %>

<div>
	<center>
	<%= link_to "<button class='button small'>#{I18n.t(:search_panel_save)}</button>".html_safe, 
    { :controller =>:dyninterface, :action=>:showsave }, "data-reveal-id" => "saveloadModal", :remote => true, :type => "button" %>	

	<%= link_to "<button class='button small'>#{I18n.t(:search_panel_load)}</button>".html_safe, 
    { :controller =>:dyninterface, :action=>:showload }, "data-reveal-id" => "saveloadModal", :remote => true, :type => "button" %>	
</center>
</div>	

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<meta http-equiv="X-UA-Compatible" content="IE=7" /> 
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=2.0" />
	 <title>  <%= content_for?(:title) ? yield(:title) : "Untitled" %> </title> 
   
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= javascript_include_tag "application" %>

	<div id="main">
	<%= render 'layouts/header'%>
	</div>
	<%= render 'layouts/navig'%> 	
		

<div class="small-12 columns">
	<% if flash[:alert].present? %>
			<div class="alert-box alert"><%= flash.alert %></div>
	<%end%>
	<% if flash[:notice].present? %>
			<div class="alert-box success"><%= flash[:notice] %></div>
	<%end%>
</div>

<!-- Content here -->
 <section id="mainContent" class="example">
<div class="row">

	<div class="small-4 columns">
	<div class="panel">
			<div id="sidebar_container1">
				<div class="sidebar1">
					<%= yield :sidebar_left %>
				</div>
		    </div>
	</div>
	</div>
	
	
	<div class="small-8 columns">
	<div class="row"> 
		<div class="panel radius">	
			<div class="content1"> <%= yield :search_results %> </div>
		</div>	
	</div>	 
	
	
	<div class="panel radius"> <%= yield %> </div>
	
	
	
	</div>
  </div>
 
</section>

<!-- Footer here --> 
<div class="row">
	 <%= render 'layouts/footer'%>
</div>
</body>
</html>